import pandas as pd
from pathlib import Path

base_dir = Path(__file__).resolve().parent
data_dir = base_dir / 'data'
output_unpivoted = base_dir / 'h1b_hub.csv.gz'

csv_files = sorted(data_dir.glob('*.csv'))
print(f'Found {len(csv_files)} CSV files')

if not csv_files:
    raise FileNotFoundError(f'No CSV files found in {data_dir}')

frames = []
for path in csv_files:
    year = int(path.stem.split()[-1])
    df = pd.read_csv(path, low_memory=False)

    rename_map = {
        'Fiscal Year   ': 'Fiscal Year',
        'Employer (Petitioner) Name': 'Employer (Petitioner) Name',
        'Industry (NAICS) Code': 'Industry (NAICS) Code',
        'Tax ID': 'Tax ID',
        'Petitioner State': 'Petitioner State',
        'Petitioner City': 'Petitioner City',
        'Petitioner Zip Code': 'Petitioner Zip Code',
        'New Employment Approval': 'New Approval',
        'New Employment Denial': 'New Denial',
        'Continuation Approval': 'Continuing Approval',
        'Continuation Denial': 'Continuing Denial',
    }

    df = df.rename(columns=rename_map)
    df['Fiscal Year'] = year

    keep_cols = [
        'Fiscal Year', 'Employer (Petitioner) Name', 'Industry (NAICS) Code', 'Tax ID', 'Petitioner State', 'Petitioner City', 'Petitioner Zip Code',
        'New Approval', 'New Denial', 'Continuing Approval', 'Continuing Denial'
    ]
    df = df[[c for c in keep_cols if c in df.columns]]
    frames.append(df)

consolidated = pd.concat(frames, ignore_index=True)
consolidated = consolidated.fillna({'Employer (Petitioner) Name': '', 'Petitioner State': '', 'Petitioner City': '', 'Petitioner Zip Code': ''})

dict_emp = {'FACEBOOK INC':'META PLATFORMS INC'
            , 'FACEBOOK SERVICES INC':'META PLATFORMS INC'
            , 'FACEBOOK SVCS INC':'META PLATFORMS INC'
            , 'FACEBOOK PAYMENTS INC':'META PLATFORMS INC'
            , 'FACEBOOK MIAMI INC':'META PLATFORMS INC'
            , 'FACEBOOKSTER INC DBA AVENUESO':'META PLATFORMS INC'


            , 'AMAZON CORPORATE LLC':'AMAZON COM SERVICES LLC'
            , 'AMAZON DEVELOPMENT CENTER U S INC':'AMAZON COM SERVICES LLC'
            , 'AMAZON WEB SERVICES INC':'AMAZON COM SERVICES LLC'
            , 'AMAZON.COM SERVICES LLC':'AMAZON COM SERVICES LLC'
            , 'AMAZON.COM SERVICES INC':'AMAZON COM SERVICES LLC'
            , 'AMAZON FULFILLMENT SERVICES INC':'AMAZON COM SERVICES LLC'
            , 'AMAZON DEVELOPMENT CENTER US INC':'AMAZON COM SERVICES LLC'
            , 'AMAZON DATA SERVICES INC':'AMAZON COM SERVICES LLC'
            , 'AMAZON GLOBAL RESOURCES INC':'AMAZON COM SERVICES LLC'
            , 'AMAZON ADVERTISING LLC':'AMAZON COM SERVICES LLC'
            , 'AMAZON ROBOTICS LLC':'AMAZON COM SERVICES LLC'
            , 'AMAZON.COM.DEDC LLC':'AMAZON COM SERVICES LLC'
            , 'AMAZON SERVICES LLC':'AMAZON COM SERVICES LLC'
            , 'AMAZON.COM.KYDC INC':'AMAZON COM SERVICES LLC'
            , 'AMAZON COM SERVICES INC':'AMAZON COM SERVICES LLC'
            , 'AMAZON PAYMENTS INC':'AMAZON COM SERVICES LLC'
            , 'AMAZON WEB SERVICES LLC':'AMAZON COM SERVICES LLC'
            , 'AMAZON.COM.KYDC LLC':'AMAZON COM SERVICES LLC'
            , 'AMAZON MECHANICAL TURK INC':'AMAZON COM SERVICES LLC'
            , 'AMAZON.COM DEDC LLC':'AMAZON COM SERVICES LLC'
            , 'AMAZON CAPITAL SERVICES INC':'AMAZON COM SERVICES LLC'
            , 'AMAZON SVCS LLC':'AMAZON COM SERVICES LLC'
            , 'AMAZON.COM KYDC LLC':'AMAZON COM SERVICES LLC'
            , 'AMAZON COM INDC LLC':'AMAZON COM SERVICES LLC'
            , 'AMAZON MEDIA GROUP LLC':'AMAZON COM SERVICES LLC'
            , 'AMAZON REGISTRY SERVICES INC':'AMAZON COM SERVICES LLC'
            , 'AMAZON COM AZDC LLC':'AMAZON COM SERVICES LLC'
            , 'AMAZON MEDIA GROUP':'AMAZON COM SERVICES LLC'
            , 'AMAZON DIGITAL SVCS INC':'AMAZON COM SERVICES LLC'
            , 'AMAZON TECHNOLOGIES INC':'AMAZON COM SERVICES LLC'
            , 'AMAZON MEDIA GROUP LLC D/B/A AMAZO':'AMAZON COM SERVICES LLC'
            , 'AMAZON DIGITAL SERVICES INC':'AMAZON COM SERVICES LLC'
            , 'AMAZON COM SVCS INC':'AMAZON COM SERVICES LLC'
            , 'AMAZON STUDIOS LLC':'AMAZON COM SERVICES LLC'
            , 'AMAZON FULFILLMENT SVCS INC':'AMAZON COM SERVICES LLC'
            , 'AMAZON COM DEDC LLC':'AMAZON COM SERVICES LLC'
            , 'AMAZON COM NVDC INC':'AMAZON COM SERVICES LLC'
            , 'AMAZON MEDIA VENTURE LLC':'AMAZON COM SERVICES LLC'
            , 'AMAZON WEB SVCS INC':'AMAZON COM SERVICES LLC'
            , 'AMAZON COM KYDC LLC':'AMAZON COM SERVICES LLC'
            , 'AMAZON.COM.CA INC':'AMAZON COM SERVICES LLC'
            , 'AMAZON FRESH LLC':'AMAZON COM SERVICES LLC'
            , 'AMAZON COM CA INC':'AMAZON COM SERVICES LLC'
            , 'AMAZON PRODUCE NETWORK LLP':'AMAZON COM SERVICES LLC'
            , 'AMAZON COM KSDC LLC':'AMAZON COM SERVICES LLC'
            , 'AMAZON CAPITAL SVCS INC':'AMAZON COM SERVICES LLC'
            , 'AMAZON PHARMACY INC':'AMAZON COM SERVICES LLC'
            , 'AMAZON DIGITAL SERVICES LLC':'AMAZON COM SERVICES LLC'
            , 'AMAZON COM AZDC INC':'AMAZON COM SERVICES LLC'
            , 'AMAZON.COM SVCS LLC F/K/A AMAZON.C':'AMAZON COM SERVICES LLC'
            , 'AMAZON COM SVCS INC F/K/A AMAZON F':'AMAZON COM SERVICES LLC'
            , 'AMAZON.COM KYDC INC':'AMAZON COM SERVICES LLC'
            , 'AMAZON REGISTRY SVCS INC':'AMAZON COM SERVICES LLC'
            , 'AMAZON.COM SERVICES LLC F/K/A AMAZON.COM SERVICES INC':'AMAZON COM SERVICES LLC'
            , 'AMAZON RETAIL LLC':'AMAZON COM SERVICES LLC'
            , 'AMAZON.COM.AZDC LLC':'AMAZON COM SERVICES LLC'
            , 'A2Z DVLP CTR INC DBA AMAZON MUSIC':'AMAZON COM SERVICES LLC'
            , 'AMAZON PRODUCE NETWORK LLC':'AMAZON COM SERVICES LLC'
            , 'AMAZON CORP LLC':'AMAZON COM SERVICES LLC'
            , 'AMAZON.COM SERVICES LLC F/K/A AMAZ':'AMAZON COM SERVICES LLC'
            , 'AMAZON CARGO INC':'AMAZON COM SERVICES LLC'
            , 'AMAZON. COM SEVS INC':'AMAZON COM SERVICES LLC'
            , 'AMAZON COM SVCS LLC FKA AMAZON':'AMAZON COM SERVICES LLC'
            , 'AMAZON MEDIA GRP LLC':'AMAZON COM SERVICES LLC'
            , 'AMAZON COM SVCS LLC F/K/A AMAZON C':'AMAZON COM SERVICES LLC'
            , 'AMAZON STUDIOS INC':'AMAZON COM SERVICES LLC'
            , 'AMAZON.COM.NVDC INC':'AMAZON COM SERVICES LLC'
            , 'AMAZON COM SERVICES INC FORMERLY K':'AMAZON COM SERVICES LLC'
            , 'AMAZON DEVELOPMENT CTR U S INC':'AMAZON COM SERVICES LLC'
            , 'AMAZON SOLUTIONS, INC.':'AMAZON COM SERVICES LLC'
            , 'AMAZON WEB SERVICE INC':'AMAZON COM SERVICES LLC'
            , 'AMAZON.COM SERVICES SERVICES INC':'AMAZON COM SERVICES LLC'
            , 'AMAZON.COM.INDC LLC':'AMAZON COM SERVICES LLC'
            , 'AMAZON WEB SREVICES INC':'AMAZON COM SERVICES LLC'
            , 'AMAZON LOGISTICS GROUP LLC':'AMAZON COM SERVICES LLC'

            , 'GOOGLE INC':'GOOGLE LLC'

            , 'COGNIZANT TECH SOLUTIONS US CORP':'COGNIZANT TECH SOLNS US CORP'
            , 'TRIZETTO CORP A COGNIZANT CO':'COGNIZANT TECH SOLNS US CORP'
            , 'COGNIZANT TECHNOLOGY SOLUTIONS US':'COGNIZANT TECH SOLNS US CORP'
            , 'COGNIZANT TECHNOLOGY SOLNS US CORP':'COGNIZANT TECH SOLNS US CORP'
            , 'COGNIZANT TECHNOLOGY SOLUTIONS US CORP':'COGNIZANT TECH SOLNS US CORP'
            , 'COGNIZANT TRIZETTO SOFTWARE GROUP':'COGNIZANT TECH SOLNS US CORP'
            , 'COGNIZANT WORLDWIDE LIMITED':'COGNIZANT TECH SOLNS US CORP'
            , 'COGNIZANT TECH SOLNS US CORP ON BE':'COGNIZANT TECH SOLNS US CORP'
            , 'COGNIZANT TRIZETTO SOFTWARE GR INC':'COGNIZANT TECH SOLNS US CORP'
            , 'TRIZETTO CORP A COGNIZANT COMPANY':'COGNIZANT TECH SOLNS US CORP'
            , 'COGNIZANT TRIZETTO SOFTWARE GRP IN':'COGNIZANT TECH SOLNS US CORP'
            , 'COGNIZANT WORLDWIDE LIMITED COGNIZ':'COGNIZANT TECH SOLNS US CORP'
            , 'TMG HEALTH A COGNIZANT COMPANY':'COGNIZANT TECH SOLNS US CORP'
            , 'COGNIZANT TECH SOLUTION US CORP':'COGNIZANT TECH SOLNS US CORP'
            , 'COGNIZANT WORLDWIDE LIMITED COGNIZANT':'COGNIZANT TECH SOLNS US CORP'
            , 'COGNIZANT TECHNOLOGY SOLUTIONS':'COGNIZANT TECH SOLNS US CORP'
            , 'COGNIZANT TECHSOLUTIONS U S CORP':'COGNIZANT TECH SOLNS US CORP'
            , 'COGNIZANT TECH SOLUTIONS CORP':'COGNIZANT TECH SOLNS US CORP'
            , 'COGNIZANT TECH SOLUTIONS US CO':'COGNIZANT TECH SOLNS US CORP'
            , 'COGNIZANT IT PROFESSIONALS INC':'COGNIZANT TECH SOLNS US CORP'
            , 'COGNIZANT':'COGNIZANT TECH SOLNS US CORP'
            , 'COGNIZANT CONSULTING CORP':'COGNIZANT TECH SOLNS US CORP'
            , 'COGNIZANT TECHNOLOGY':'COGNIZANT TECH SOLNS US CORP'
            , 'COGNIZANT TECHNOLOGY SOLN US CORP':'COGNIZANT TECH SOLNS US CORP'
            , 'COGNIZANT TECH SOLUTIONS  US CORP':'COGNIZANT TECH SOLNS US CORP'
            , 'COGNIZANT TECH SOLNS SR US CORP':'COGNIZANT TECH SOLNS US CORP'
            , 'COGNIZANT TECH SOLNS CORP':'COGNIZANT TECH SOLNS US CORP'
            , 'COGNIZANTS TECH SOLUTIONS US CORP':'COGNIZANT TECH SOLNS US CORP'
            , 'ITAAS INC ITAAS C/O COGNIZANT TECH':'COGNIZANT TECH SOLNS US CORP'
            , 'ITAAS INC COGNIZANT TECHNOLOGY SOL':'COGNIZANT TECH SOLNS US CORP'
            , 'COGNIZANT TECHNOLOGY SOLUTIONS GRP':'COGNIZANT TECH SOLNS US CORP'
            , 'COGNIZANT TECHNOLOGY SOLUTIONS UC':'COGNIZANT TECH SOLNS US CORP'
            , 'COGNIZANT MOBILITY INC':'COGNIZANT TECH SOLNS US CORP'
            , 'COGNIZANT WORLDWIDE LTD COGNIZANT':'COGNIZANT TECH SOLNS US CORP'
            , 'TMG HEALTH A COGNIZANT CO-HQ 25 LA':'COGNIZANT TECH SOLNS US CORP'
            , 'TMG HEALTH INC A COGNIZANT COMPANY - HQ':'COGNIZANT TECH SOLNS US CORP'
            , 'COGNIZANT TRIZETTO SOFTWARE GROUP INC CTSG':'COGNIZANT TECH SOLNS US CORP'
            , 'TMG HEALTH INC A COGNIZANT COMPANY':'COGNIZANT TECH SOLNS US CORP'

            , 'TATA CONSULTANCY SERVICES LIMITED':'TATA CONSULTANCY SVCS LTD'
            , 'TATA TECHNOLOGIES INC':'TATA CONSULTANCY SVCS LTD'
            , 'TATA ELXSI LIMITED':'TATA CONSULTANCY SVCS LTD'
            , 'TATA COMMUNICATIONS AMERICA INC':'TATA CONSULTANCY SVCS LTD'
            , 'TATA AMERICA INTERNATIONAL CORP':'TATA CONSULTANCY SVCS LTD'
            , 'TATA TECHNOLOGIES INC TTI':'TATA CONSULTANCY SVCS LTD'
            , 'TATA INTERNATIONAL CORPORATION':'TATA CONSULTANCY SVCS LTD'
            , 'TATA TECHS INC':'TATA CONSULTANCY SVCS LTD'
            , 'TATA COMMUNICATIONS (AMERICA) INC':'TATA CONSULTANCY SVCS LTD'
            , 'TATA INTERACTIVE SYSTEMS USA':'TATA CONSULTANCY SVCS LTD'
            , 'TATA AUTOCOMP SYSTEMS LTD':'TATA CONSULTANCY SVCS LTD'
            , 'TATA ELXSI LTD':'TATA CONSULTANCY SVCS LTD'
            , 'TATA AUTOCOMP SYSTEMS LIMITED':'TATA CONSULTANCY SVCS LTD'
            , 'TATA CONSULTANCY SVCS LIMITED':'TATA CONSULTANCY SVCS LTD'
            , 'TATA CONSULTANCY SERVICES LTD':'TATA CONSULTANCY SVCS LTD'
            , 'TATA INTERACTIVE SYSTEMS':'TATA CONSULTANCY SVCS LTD'
            , 'TATA CHEMICALS SODA ASH PARTNERS':'TATA CONSULTANCY SVCS LTD'
            , 'TATA AMERICA INTL CORP':'TATA CONSULTANCY SVCS LTD'
            , 'TATA CONSUTANCY SVCS LTD':'TATA CONSULTANCY SVCS LTD'
            , 'TATA CONSULTING ENGINEERS LTD':'TATA CONSULTANCY SVCS LTD'
            , 'TATA CHEMICALS NORTH AMERICA INC':'TATA CONSULTANCY SVCS LTD'
            , 'TATA INTL METALS AMERICAS LTD':'TATA CONSULTANCY SVCS LTD'
            , 'TATA BUSINESS SUPPORT SERVICES LTD':'TATA CONSULTANCY SVCS LTD'
            , 'TATA JOHNSON SYSTEMS ENGINEERING L':'TATA CONSULTANCY SVCS LTD'
            , 'TATA AMERICA INTL CORPORATION':'TATA CONSULTANCY SVCS LTD'
            , 'TATA COSULTANCY SVCS LTD':'TATA CONSULTANCY SVCS LTD'
            , 'TATA STEEL INTL AMERICAS INC':'TATA CONSULTANCY SVCS LTD'
            , 'TATA BUSINESS SUPPORT SVCS LIMITED':'TATA CONSULTANCY SVCS LTD'
            , 'TATA AM INTL CORP DBA TCS AMERICA':'TATA CONSULTANCY SVCS LTD'
            , 'TATA ENTERPRISES INC':'TATA CONSULTANCY SVCS LTD'
            , 'TATA STEEL INTERNATIONAL NORTH AME':'TATA CONSULTANCY SVCS LTD'
            , 'TATA E-SERVE INTERNATIONAL LIMITED':'TATA CONSULTANCY SVCS LTD'
            , 'TATA CHEMICALS NORTH AMERICA':'TATA CONSULTANCY SVCS LTD'
            , 'TATA AUTOCOMP SYSTEMS NA':'TATA CONSULTANCY SVCS LTD'
            , 'TATA CONSULTANCY SVCS LTE':'TATA CONSULTANCY SVCS LTD'
            , 'TATA COMMUNICATIONS SVC AMERICA IN':'TATA CONSULTANCY SVCS LTD'
            , 'TATA CONCULTANCY SVCS LTD':'TATA CONSULTANCY SVCS LTD'

            , 'WIPRO VLSI DESIGN SERVICES LLC':'WIPRO LIMITED'
            , 'WIPRO LTD':'WIPRO LIMITED'
            , 'WIPRO APPIRIO INC':'WIPRO LIMITED'
            , 'WIPRO TECHNOLOGIES':'WIPRO LIMITED'
            , 'WIPROSOLUTIONS INC':'WIPRO LIMITED'
            , 'WIPRO LIMTED':'WIPRO LIMITED'
            , 'WIPRO DATA CTR & CLOUD SERVICES IN':'WIPRO LIMITED'
            , 'WIPRO LLC':'WIPRO LIMITED'

            , 'INFOSYS LTD':'INFOSYS LIMITED'
            , 'KPIT INFOSYSTEMS INC':'INFOSYS LIMITED'
            , 'INFOSYS TECHNOLOGIES LIMITED':'INFOSYS LIMITED'
            , 'INFOSYS SOLUTIONS INC':'INFOSYS LIMITED'
            , 'INFOSYS BPO LIMITED':'INFOSYS LIMITED'
            , 'AMERICAN INFOSYS INC':'INFOSYS LIMITED'
            , 'PROSPECT INFOSYS INC':'INFOSYS LIMITED'
            , 'INFOSYS PUBLIC SERVICES':'INFOSYS LIMITED'
            , 'INFOSYS BPM LIMITED':'INFOSYS LIMITED'
            , 'SIERRA INFOSYS INC':'INFOSYS LIMITED'
            , 'SRIVEN INFOSYS INC':'INFOSYS LIMITED'
            , 'INFOSYS CONSULTING INC':'INFOSYS LIMITED'
            , 'INFOSYS PUBLIC SERVICES INC':'INFOSYS LIMITED'
            , 'INFOSYS BPO LTD':'INFOSYS LIMITED'
            , 'INFOSYS MCCAMISH SYSTEMS LLC':'INFOSYS LIMITED'
            , 'VECTRA INFOSYS INC':'INFOSYS LIMITED'
            , 'B2B INFOSYS INC':'INFOSYS LIMITED'
            , 'PLATINUM INFOSYS INC':'INFOSYS LIMITED'
            , 'SUNRAY INFOSYS INCORPORATION':'INFOSYS LIMITED'
            , 'ICONIC INFOSYS INC':'INFOSYS LIMITED'
            , 'INFOSYS INTERNATIONAL INC':'INFOSYS LIMITED'
            , 'SUNRAY INFOSYS INC':'INFOSYS LIMITED'
            , 'CUBE INFOSYS LLC':'INFOSYS LIMITED'
            , 'LN INFOSYS INC':'INFOSYS LIMITED'
            , 'RAVE INFOSYS INC':'INFOSYS LIMITED'

            , 'ACCENTURE TECHNOLOGY SOLUTIONS':'ACCENTURE LLP'
            , 'ACCENTURE TECH SOLUTIONS':'ACCENTURE LLP'
            , 'ACCENTURE INC':'ACCENTURE LLP'
            , 'ACCENTURE GLOBAL INC':'ACCENTURE LLP'
            , 'ACCENTURE LLP DBA IMAGINEA TECH':'ACCENTURE LLP'

            , 'HCL GLOBAL SYSTEMS INC':'HCL AMERICA INC'
            , 'HCL AMERICA SOLUTIONS INC':'HCL AMERICA INC'
            , 'HCL SYSTEMS INC':'HCL AMERICA INC'
            , 'HCL INFOSERV INC':'HCL AMERICA INC'
            , 'HCL INFOSERV INC DBA HBL INFOSERV':'HCL AMERICA INC'
            , 'HCL GLOBAL SYS INC':'HCL AMERICA INC'

            , 'DELOITTE & TOUCHE LLP':'DELOITTE CONSULTING LLP'
            , 'DELOITTE AND TOUCHE LLP':'DELOITTE CONSULTING LLP'
            , 'DELOITTE TAX LLP':'DELOITTE CONSULTING LLP'
            , 'DELOITT& TOUCHE LLP':'DELOITTE CONSULTING LLP'
            , 'DELOITTE TRANSACTIONS & BUS ANALYT':'DELOITTE CONSULTING LLP'
            , 'DELOITTE SERVICES LP':'DELOITTE CONSULTING LLP'
            , 'DELOITTE TOUCHE TOHMATSU SVCS INC':'DELOITTE CONSULTING LLP'
            , 'DELOITTE FINANCIAL ADVISORY SVCS L':'DELOITTE CONSULTING LLP'
            , 'DELOITTE TOUCHE TOHMATSU SVCS LLC':'DELOITTE CONSULTING LLP'
            , 'DELOITTE TOUCHE TOHMATSU SERVICES LLC':'DELOITTE CONSULTING LLP'
            , 'DELOITTE LLP':'DELOITTE CONSULTING LLP'
            , 'DELOITTE TRANSACTIONS AND BUSINESS ANALYTICS LLP':'DELOITTE CONSULTING LLP'
            , 'DELOITTE FINANCIAL ADVISORY SVCS':'DELOITTE CONSULTING LLP'
            , 'DELOITTE CONSULTING EXTENDED B':'DELOITTE CONSULTING LLP'
            , 'DELOITTE SVCS LP':'DELOITTE CONSULTING LLP'
            , 'DELOITTE FIN ADVISORY SVCS LLP':'DELOITTE CONSULTING LLP'
            , 'DELOITTE TOUCHE TOHMATSU SVCS IN':'DELOITTE CONSULTING LLP'
            , 'DELOITTE CONSULTING EXTENDED':'DELOITTE CONSULTING LLP'
            , 'DELOITTE CORPORATE FINANCE LLC':'DELOITTE CONSULTING LLP'
            , 'DELOITTE & TOUCHE LLC':'DELOITTE CONSULTING LLP'
            , 'DELOITTE CONSULTING OVERSEAS PROJE':'DELOITTE CONSULTING LLP'
            , 'DELOITTE ANALYTICS LLC':'DELOITTE CONSULTING LLP'
            , 'DELOITTE CONSULTING OVERSEAS':'DELOITTE CONSULTING LLP'
            , 'DELOITTE FINANCIAL ADVISORY SERVICES LLP':'DELOITTE CONSULTING LLP'
            , 'DELOITTE MARKETPOINT LLC':'DELOITTE CONSULTING LLP'
            , 'DELOITTE LLP-DELOITTE LLP':'DELOITTE CONSULTING LLP'
            , 'DELOITTE FIN ADVISORY SERVICES LLP':'DELOITTE CONSULTING LLP'
            , 'DELOITTE TOUCHE TOHMATSU SERVICES':'DELOITTE CONSULTING LLP'
            , 'DELOITTE SERVICES LLP':'DELOITTE CONSULTING LLP'
            , 'DELOITTE CONSULTING':'DELOITTE CONSULTING LLP'
            , 'DELOITTE CONS OVERSEAS PROJECTS LL':'DELOITTE CONSULTING LLP'
            , 'DELOITTE CONSULTING OVERSEAS SVCS':'DELOITTE CONSULTING LLP'
            , 'DELOITTE INVESTMENTS LLC':'DELOITTE CONSULTING LLP'
            , 'DELOITTE TRANSACTION & BUS ANALYTI':'DELOITTE CONSULTING LLP'
            , 'DELOITTE COSULTING LLP':'DELOITTE CONSULTING LLP'
            , 'DELOITTE CONSULTING OVERS':'DELOITTE CONSULTING LLP'
            , 'DELOITTE FINANCIAL ADVISORY SERVIC':'DELOITTE CONSULTING LLP'
            , 'DELOITTE & TOUCHE OVERSEAS PROJECT':'DELOITTE CONSULTING LLP'
            , 'DELOITTE TAX OVERSEAS SVCS LLC':'DELOITTE CONSULTING LLP'
            , 'DELOITTE TOUCHE LLP':'DELOITTE CONSULTING LLP'
            , 'DELOITTE TRANSACTIONS AND BUSINESS':'DELOITTE CONSULTING LLP'
            , 'DELOITTE TOUCHE OVERSEAS PROJECTS':'DELOITTE CONSULTING LLP'
            , 'DELOITTE CONS OVERSEAS PROJECT LLC':'DELOITTE CONSULTING LLP'
            , 'DELOITTE TAX OVERSEAS SERVICES LLC':'DELOITTE CONSULTING LLP'
            , 'DELOITTE & TOUCHE USA OVERSEAS SVC':'DELOITTE CONSULTING LLP'
            , 'DELOITTE SVCS OVERSEAS SVCS LLC':'DELOITTE CONSULTING LLP'
            , 'DELOITTE CORP FINANCE LLC':'DELOITTE CONSULTING LLP'
            , 'DELOITTE & TOUCHE OVERSEAS SVCS LL':'DELOITTE CONSULTING LLP'
            , 'DELOITTE FINANCIAL ADVISORY SRVCS':'DELOITTE CONSULTING LLP'

            , 'CAPGEMINI FINANCIAL SVCS USA INC':'CAPGEMINI AMERICA INC'
            , 'CAPGEMINI US LLC':'CAPGEMINI AMERICA INC'
            , 'CAPGEMINI U S LLC':'CAPGEMINI AMERICA INC'
            , 'CAPGEMINI FINANCIAL SVCS USA INC (':'CAPGEMINI AMERICA INC'
            , 'CAPGEMINI FINANCIAL SERVICES USA':'CAPGEMINI AMERICA INC'
            , 'CAPGEMINI AMERICA INC THROUGH ITS':'CAPGEMINI AMERICA INC'
            , 'CAPGEMINI':'CAPGEMINI AMERICA INC'
            , 'CAPGEMINI GOVERNMENT SOLUTIONS LLC':'CAPGEMINI AMERICA INC'
            , 'CAPGEMINI APPLICATION SERVICES LLC':'CAPGEMINI AMERICA INC'
            , 'CAPGEMINI FINANCIAL SVCS USA INC L':'CAPGEMINI AMERICA INC'
            , 'CAPGEMINI FINANCIAL SERVICES USA I':'CAPGEMINI AMERICA INC'
            , 'CAPGEMINI APPLICATIONS SVCS LLC':'CAPGEMINI AMERICA INC'
            , 'CAPGEMINI ENERGY LP':'CAPGEMINI AMERICA INC'
            , 'CAPGEMINI AMERICAS INC':'CAPGEMINI AMERICA INC'
            , 'CAPGEMINI GOVT SOLUTIONS LLC':'CAPGEMINI AMERICA INC'
            , 'CAPGEMINI FIN. SERVICES USA INC':'CAPGEMINI AMERICA INC'
            , 'CAPGEMINI GOVERMENT SOLUTIONS LLC':'CAPGEMINI AMERICA INC'

            , 'TECH MAHINDRA (AMERICAS) INC':'TECH MAHINDRA AMERICAS INC'
            , 'TECH MAHINDRA TECHNOLOGIES INC':'TECH MAHINDRA AMERICAS INC'
            , 'TECH MAHINDRA INC':'TECH MAHINDRA AMERICAS INC'
            , 'TECH MAHINDRA NETWORK SERVICES INT':'TECH MAHINDRA AMERICAS INC'
            , 'TECH MAHINDRA NETWORK SVCS INTL IN':'TECH MAHINDRA AMERICAS INC'
            , 'TECH MAHINDRA CERIUM SYSTEMS INC':'TECH MAHINDRA AMERICAS INC'
            , 'TECH MAHINDRA TECHNOLOGIES IN':'TECH MAHINDRA AMERICAS INC'
            , 'TECH MAHINDRA NETWORK SERVICES INTERNATIONAL INC FORMERLY LLC INTERNATIONAL INC':'TECH MAHINDRA AMERICAS INC'
            , 'TECH MAHINDRA NETWORK SERVICES':'TECH MAHINDRA AMERICAS INC'
            , 'TECH MAHINDRA NETWORK SVCS INTL':'TECH MAHINDRA AMERICAS INC'
            , 'TECH MAHINDRA NTWRK SVCS INTL INC':'TECH MAHINDRA AMERICAS INC'
            , 'TECH MAHINDRAS AMERICAS INC':'TECH MAHINDRA AMERICAS INC'
            , 'TECH MAHINDRA R & D SERVICES INC':'TECH MAHINDRA AMERICAS INC'
            , 'TECH MAHINDRA AMERICANS INC':'TECH MAHINDRA AMERICAS INC'

            , 'IBM INDIA PRIVATE LIMITED':'IBM CORPORATION'
            , 'IBM INDIA PVT LTD':'IBM CORPORATION'
            , 'IBM CORP':'IBM CORPORATION'
            , 'IBM GLOBAL SYSTEMS DBA JOLT TECHS':'IBM CORPORATION'
            , 'IBM GLOBAL SYSTEMS INC DBA JOLT TE':'IBM CORPORATION'
            , 'IBM GLOBAL SYSS INC DBA JOLT TECHS':'IBM CORPORATION'
            , 'IBM INDIA PRIVATE LTD':'IBM CORPORATION'
            , 'IBM GLOBAL SYSTEMS INC':'IBM CORPORATION'
            , 'IBM GLOBAL SYSS INC DBA JOLT TECH':'IBM CORPORATION'
            , 'IBM SOUTHEAST EMPLOYEES FEDERAL':'IBM CORPORATION'
            , 'SOFTLAYER AN IBM COMPANY':'IBM CORPORATION'
            , 'UNICA CORPORATION AN IBM COMPANY':'IBM CORPORATION'
            , 'IBM INDIAN PRIVATE LIMITED':'IBM CORPORATION'
            , 'IBM GLOBAL SYSTEMS INC DBA JOLT':'IBM CORPORATION'
            , 'IBM INDIA PRIVATE LIMTIED':'IBM CORPORATION'
            , 'IBM INDIA PRIVATE LITD':'IBM CORPORATION'
            , 'IBM':'IBM CORPORATION'
            , 'KENEXA TECHNOLOGY INC/IBM':'IBM CORPORATION'


            , 'MICROSOFT CORP':'MICROSOFT CORPORATION'
            , 'MICROSOFT LICENSING GP':'MICROSOFT CORPORATION'
            , 'MICROSOFT ONLINE INC':'MICROSOFT CORPORATION'
            , 'MICROSOFT OPS PUERTO RICO LLC':'MICROSOFT CORPORATION'
            , 'MICROSOFT PAYMENTS INC':'MICROSOFT CORPORATION'
            , 'MICROSOFT':'MICROSOFT CORPORATION'
            , 'MICROSOFT CARIBBEAN INC':'MICROSOFT CORPORATION'
            , 'MICROSOFT CORPORATIOIN':'MICROSOFT CORPORATION'
            , 'MICROSOFT OPEN TECHNOLOGIES INC':'MICROSOFT CORPORATION'
            , 'MICROSOFT CORPORTION':'MICROSOFT CORPORATION'

            , 'ERNST YOUNG US LLP':'ERNST & YOUNG US LLP'
            , 'ERNST AND YOUNG U S LLP':'ERNST & YOUNG US LLP'
            , 'ERNST & YOUNG LLP':'ERNST & YOUNG US LLP'
            , 'ERNST & YOUNG U S LLP':'ERNST & YOUNG US LLP'
            , 'ERNST & YOUNG LLP EY GUAM':'ERNST & YOUNG US LLP'
            , 'ERNST YOUNG U S LLP':'ERNST & YOUNG US LLP'
            , 'ERNST & YOUNG LLP CNMI INC':'ERNST & YOUNG US LLP'
            , 'ERNST & YOUNG CNMI INC':'ERNST & YOUNG US LLP'
            , 'ERNST & YOUNG EY GUAM':'ERNST & YOUNG US LLP'
            , 'ERNST YOUNG US CORP LLP':'ERNST & YOUNG US LLP'
            , 'ERNST YOUNG LLP':'ERNST & YOUNG US LLP'
            , 'ERNST AND YOUNG US LLP':'ERNST & YOUNG US LLP'

            , 'INTEL CORPORATION':'INTEL CORPORATION'
            , 'INTEL CORP':'INTEL CORPORATION'

            , 'JPMORGAN CHASE & CO':'JPMORGAN CHASE & CO'
            , 'JPMORGAN CHASE CO':'JPMORGAN CHASE & CO'
            , 'JPMORGAN CHASE AND CO':'JPMORGAN CHASE & CO'
            , 'JPMORGAN CHASE & CO.':'JPMORGAN CHASE & CO'

            , 'PRICEWATERHOUSECOOPERS LLP':'PRICEWATERHOUSECOOPERS LLP'
            , 'PRICEWATERHOUSECOOPERS ADVISORY SE':'PRICEWATERHOUSECOOPERS LLP'
            , 'PRICEWATERHOUSECOOPERS ADVISORY LL':'PRICEWATERHOUSECOOPERS LLP'

            , 'NVIDIA CORPORATION':'NVIDIA CORPORATION'
            , 'NVIDIA CORP':'NVIDIA CORPORATION'

            , 'QUALCOMM TECHNOLOGIES INC':'QUALCOMM TECHNOLOGIES INC'
            , 'QUALCOMM INCORPORATED':'QUALCOMM TECHNOLOGIES INC'
            , 'QUALCOMM ATHEROS INC':'QUALCOMM TECHNOLOGIES INC'
            , 'QUALCOMM INNOVATION CENTER INC':'QUALCOMM TECHNOLOGIES INC'

           }

consolidated["Employer (Petitioner) Name"] = consolidated["Employer (Petitioner) Name"].replace(dict_emp)  

value_columns = ['New Approval', 'New Denial', 'Continuing Approval', 'Continuing Denial']
for col in value_columns:
    consolidated[col] = pd.to_numeric(consolidated[col], errors='coerce').fillna(0).astype('int32')

consolidated['Fiscal Year'] = consolidated['Fiscal Year'].astype('int16')

for col in ['Employer (Petitioner) Name', 'Industry (NAICS) Code', 'Petitioner State', 'Petitioner City', 'Petitioner Zip Code']:
    if col in consolidated.columns and consolidated[col].nunique(dropna=False) <= max(1000, len(consolidated) // 10):
        consolidated[col] = consolidated[col].astype('category')

# Remove any existing output file first to avoid permission issues in the notebook environment
if output_unpivoted.exists():
    output_unpivoted.unlink()

unpivoted = consolidated.melt(
    id_vars=['Fiscal Year', 'Employer (Petitioner) Name', 'Tax ID', 'Industry (NAICS) Code', 'Petitioner City', 'Petitioner State', 'Petitioner Zip Code'],
    value_vars=value_columns,
    var_name='Pivot Field Names',
    value_name='Pivot Field Values'
)
unpivoted = unpivoted.sort_values(['Fiscal Year', 'Employer (Petitioner) Name', 'Pivot Field Names']).reset_index(drop=True)
unpivoted['Fiscal Year'] = unpivoted['Fiscal Year'].astype('int16')
unpivoted['Pivot Field Names'] = unpivoted['Pivot Field Names'].astype('category')
unpivoted['Pivot Field Values'] = unpivoted['Pivot Field Values'].astype('int32')
unpivoted.to_csv(output_unpivoted, index=False, compression='gzip')
print(f'Saved unpivoted CSV to {output_unpivoted}')
